-- ============================================================================
-- BIZRISE — Stored Procedures (Migrados a PostgreSQL)
-- ============================================================================
-- NOTA: Este proyecto ahora usa consultas SQL directas desde los repositorios.
-- Los SPs ya no se ejecutan. Este archivo se mantiene como referencia.
--
-- Migración completada: Junio 2026
-- SQL Server (EXEC sp_name @params) → PostgreSQL (queries directas con %(params)s)
-- ============================================================================
--
-- Cambios aplicados directamente en src/repositories/:
--   * SCOPE_IDENTITY() → RETURNING
--   * GETDATE() → NOW()
--   * ISNULL() → COALESCE()
--   * TOP n → LIMIT n
--   * OFFSET FETCH → LIMIT/OFFSET
--   * #temp → CTEs
--   * BIT → BOOLEAN
--   + VARCHAR(MAX) → TEXT
--   + + para concatenar → CONCAT()
--
-- Ver schema.sql para PostgreSQL y los repositorios para las queries.
-- ============================================================================
